### ISSUE TITLE
Open Police Data Explorer

### ISSUE THREAD

**Issue by daniellekushner** [openpolicedata/OPD_Explorer#45]
Hello!

I'm trying to use the Open Police Data Explorer but it keeps crashing. Is there something I can do to fix this?

Thank you,

Danielle Kushner
dkushner@policingequity.org

**Comment by sowdm** [comment]
@daniellekushner There seems to have been an issue with the host's server. I rebooted the app, and it appears to be working again. Please let me know if you are able to access it successfully now.

**Comment by sowdm** [comment]
The app has crashed again. Thank you for bringing this to my attention. I will look into it and see what is causing this and let you know when it is taken care of.

**Comment by daniellekushner** [comment]
Thank you!

**Comment by sowdm** [comment]
It's been running for over a day now with no issues. I've downloaded various datasets, both big and small, with no issues. It seems to have been an issue with the host as I didn't need to change anything.

Please try again let me know if you are able to access everything OK: https://openpolicedata.streamlit.app/

**Comment by sowdm** [comment]
Added code to handle all known edge cases when filtering data sources in 65fc835c60f4d0cdd2beabeb041b111b67da32ee
